# Generated by Django 2.2.1 on 2019-08-13 21:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GbifSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetName', models.TextField()),
                ('common', models.TextField()),
                ('redList', models.TextField()),
                ('kingdom', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('recency', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
