# Generated by Django 2.2.1 on 2019-06-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('species', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('y_1990', models.IntegerField(db_column='1990')),
                ('y_1991', models.IntegerField(db_column='1991')),
                ('y_1992', models.IntegerField(db_column='1992')),
            ],
        ),
    ]
