# Generated by Django 2.2.1 on 2019-06-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='y_1990',
        ),
        migrations.RemoveField(
            model_name='year',
            name='y_1991',
        ),
        migrations.RemoveField(
            model_name='year',
            name='y_1992',
        ),
    ]
