# Generated by Django 2.2.1 on 2019-08-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifsummary',
            old_name='location',
            new_name='point',
        ),
    ]
