# Generated by Django 2.2.1 on 2019-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0002_auto_20190813_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbifsummary',
            name='family',
        ),
        migrations.RemoveField(
            model_name='gbifsummary',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='gbifsummary',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='gbifsummary',
            name='order',
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_class',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_family',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_genus',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_kingdom',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_order',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='t_phylum',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gbifsummary',
            name='common',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gbifsummary',
            name='datasetName',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gbifsummary',
            name='recency',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gbifsummary',
            name='redList',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gbifsummary',
            name='species',
            field=models.TextField(default=None),
        ),
    ]
