# Generated by Django 2.2.1 on 2019-08-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0003_auto_20190813_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifsummary',
            old_name='datasetName',
            new_name='datasetname',
        ),
    ]
