# Generated by Django 2.2.1 on 2019-06-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0004_auto_20190625_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'managed': True},
        ),
    ]
