# Generated by Django 2.2.1 on 2019-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0005_auto_20190813_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbifsummary',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=30),
        ),
        migrations.AddField(
            model_name='gbifsummary',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=30),
        ),
    ]
