# Generated by Django 2.2.1 on 2019-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0005_auto_20190625_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('phone', models.TextField(unique=True)),
                ('tel', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
