# Generated by Django 2.2.1 on 2019-06-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0006_auto_20190625_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
