# Generated by Django 2.2.1 on 2019-08-15 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0006_auto_20190814_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifSummaryFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetname', models.TextField(default=None)),
                ('species', models.TextField(default=None)),
                ('lon', models.DecimalField(decimal_places=6, default=None, max_digits=30)),
                ('lat', models.DecimalField(decimal_places=6, default=None, max_digits=30)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('year', models.IntegerField(default=None, max_length=4)),
            ],
        ),
    ]
