# Generated by Django 2.2.1 on 2019-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0008_speciesyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1700',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1800',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1818',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1856',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1857',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1859',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1860',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1872',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1874',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1875',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1876',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1877',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1878',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1879',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1880',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1881',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1882',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1883',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1884',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1885',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1886',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1887',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1888',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1889',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1890',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1891',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1892',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1893',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1894',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1895',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1896',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1897',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1898',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1899',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1900',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1901',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1902',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1903',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1904',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1905',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1906',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1907',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1908',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1909',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1910',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1911',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1912',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1913',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1914',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1915',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1916',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1917',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1918',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1919',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1920',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1921',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1922',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1923',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1924',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1925',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1926',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1927',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1928',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1929',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1930',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1931',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1932',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1933',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1934',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1935',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1936',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1937',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1938',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1939',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1940',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1941',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1942',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1943',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1944',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1945',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1946',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1947',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1948',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1949',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1950',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1951',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1952',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1953',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1954',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1955',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1956',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1957',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1958',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1959',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1960',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1961',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1962',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1963',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1964',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1965',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1966',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1967',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1968',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1969',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1970',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1971',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1972',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1973',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1974',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1975',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1976',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1977',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1978',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1979',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1980',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1981',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1982',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1983',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1984',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1985',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1986',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1987',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1988',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1989',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1990',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1991',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1992',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1993',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1994',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1995',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1996',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1997',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1998',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_1999',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2000',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2001',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2002',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2003',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2004',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2005',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2006',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2007',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2008',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2009',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2010',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2011',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2012',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2013',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2014',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2015',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2016',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2017',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2018',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesyear',
            name='year_2019',
            field=models.TextField(blank=True, null=True),
        ),
    ]
