# Generated by Django 2.2.1 on 2019-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0009_auto_20190626_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesRecency',
            fields=[
                ('species', models.TextField(primary_key=True, serialize=False)),
                ('recent', models.TextField(blank=True, null=True)),
                ('old', models.TextField(blank=True, null=True)),
                ('both', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
