# Generated by Django 2.2.1 on 2019-07-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodivmap', '0010_speciesrecency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeciesRecency',
        ),
        migrations.DeleteModel(
            name='SpeciesYear',
        ),
    ]
